### ISSUE TITLE
Distrinet setup and experiments from a YAML file

### ISSUE THREAD

**Issue by atomassi** [Giuseppe1992/Distrinet#3]
##  Making network experiments simpler ## 

Instead of defining the experiment through a Python script or using the Mininet-style CLI, an alternative way may consist in using the `YAML` format (in ansible style) in which the user is able to specify the virtual topology to be used and all its properties.

- The network type (e.g., custom, fat-tree, and complete mesh).
- The properties in terms of physical requirements for both virtual nodes and links.
 
File format
---

A possible format is as follows.

#### topo.yml

```yaml
topo:
  type: custom
  nodes:
    - id: 1
      type: switch
      cores: 3
      memory: 2
      memory_unit: Gb
    - id: 2
      type: host
      cores: 3
      memory: 2
      memory_unit: Gb
    - id: 3
      type: host
      cores: 3
      memory: 2
      memory_unit: Gb

  links:
    - source: 1
      target: 2
      bandwidth: 100
      bandwidth_unit: Mbps
    - source: 1
      target: 3
      bandwidth: 100
      bandwidth_unit: Mbps

```

Defining the experiment
---
In addition, it could be nice to be able to directly specify the experiment settings and the results to be returned.

- Where to run the experiment (Amazon, Grid5k, etc )
- Properties for the experiment (duration, etc)
- Metrics to be studied (delay, load, etc)
- Scenarios (failures, reconfigurations, etc)
- ...
   
An example might be the following one:

```yaml
experiments:
  setup:
      name: aws
      aws_access_key_id: XXX
      aws_secret_access_key: YYY

  scenarios:
    - name: exp 1
      description: study delay and load

      demands:
        - source: 1
          target: 3
          rate: 100
          rate_unit: Mbps
          
      duration:
        time: 60
        time_unit: sec
        
      metrics:
        - delay
        - cpu load
```

Parsing the file
---
Dependencies:
```python
pip install pyyaml
```
Reading the file

```python
with open("topo.yaml", "r") as stream:
    data = yaml.safe_load(stream)
```

which results in the following dictionary:

    {
        "topo": {
            "type": "custom",
            "nodes": [
                {"id": 1, "type": "switch", "cores": 3, "memory": 2, "memory_unit": "Gb"},
                {"id": 2, "type": "host", "cores": 3, "memory": 2, "memory_unit": "Gb"},
                {"id": 3, "type": "host", "cores": 3, "memory": 2, "memory_unit": "Gb"},
            ],
            "links": [
                {"source": 1, "target": 2, "bandwidth": 100, "bandwidth_unit": "Mbps"},
                {"source": 1, "target": 3, "bandwidth": 100, "bandwidth_unit": "Mbps"},
            ],
        },
        "experiments": {
            "setup": {
                "name": "aws",
                "aws_access_key_id": "XXXXXXXXXXXXXXXXX",
                "aws_secret_access_key": "YYYYYYYYYYYYYYYYYYYYYY",
            },
            "scenarios": [
                {
                    "name": "exp 1",
                    "description": "study delay and load",
                    "demands": [
                        {"source": 1, "target": 3, "rate": 100, "rate_unit": "Mbps"}
                    ],
                    "duration": {"time": 60, "time_unit": "sec"},
                    "metrics": ["delay", "cpu load"],
                }
            ],
        },
    }

---
This is just a suggestion, the best format and style for the file need to be chosen according to the available features.
